package com.example.myapplication.ui.screens.anniversary

import android.graphics.Color as AndroidColor
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.myapplication.data.AppDatabase
import com.example.myapplication.data.Event
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.time.temporal.ChronoUnit

@Composable
fun AnniversaryScreen() {
    val context = LocalContext.current
    val database = remember { AppDatabase.getDatabase(context) }
    val profileDao = remember { database.profileDao() }
    val eventDao = remember { database.eventDao() }
    val scope = rememberCoroutineScope()
    
    var relationshipStartDate by remember { mutableStateOf<LocalDate?>(null) }
    var userAnniversaries by remember { mutableStateOf(listOf<Event>()) }
    var showAddDialog by remember { mutableStateOf(false) }
    
    // 프로필에서 사귀기 시작한 날 가져오기
    LaunchedEffect(Unit) {
        try {
            val profile = profileDao.getProfile().first()
            if (profile?.relationshipStartDate?.isNotEmpty() == true) {
                try {
                    relationshipStartDate = LocalDate.parse(
                        profile.relationshipStartDate,
                        DateTimeFormatter.ISO_LOCAL_DATE
                    )
                } catch (e: Exception) {
                    relationshipStartDate = null
                }
            }
        } catch (e: Exception) {
            relationshipStartDate = null
        }
        
        // 사용자가 추가한 기념일 불러오기
        try {
            eventDao.getAllEvents().collect { events ->
                userAnniversaries = events.filter { it.isAnniversary }
            }
        } catch (e: Exception) {
            userAnniversaries = emptyList()
        }
    }
    
    // 자동 기념일 계산
    val autoAnniversaries = remember(relationshipStartDate) {
        relationshipStartDate?.let { startDate ->
            calculateAutoAnniversaries(startDate)
        } ?: emptyList()
    }
    
    // 전체 기념일 목록 (자동 + 사용자 추가)
    val allAnniversaries = remember(autoAnniversaries, userAnniversaries) {
        val combined = autoAnniversaries + userAnniversaries.map { event ->
            Anniversary(
                id = event.id,
                title = event.title,
                date = event.date,
                color = event.color.ifBlank { DEFAULT_ANNIVERSARY_COLOR_HEX },
                isAutoGenerated = false
            )
        }
        combined.sortedBy { it.date }
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFFFFF5F5))
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(20.dp)
        ) {
            // 헤더
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Text(
                        text = "기념일",
                        style = MaterialTheme.typography.headlineMedium.copy(
                            fontWeight = FontWeight.Bold,
                            fontSize = 24.sp
                        ),
                        color = Color(0xFF5D4037)
                    )
                    Text(
                        text = "🎉",
                        fontSize = 20.sp
                    )
                }
            }

            Spacer(modifier = Modifier.height(8.dp))

            Text(
                text = "우리의 소중한 날들을 기록해요 ✨",
                style = MaterialTheme.typography.bodyMedium,
                color = Color(0xFF5D4037)
            )

            Spacer(modifier = Modifier.height(32.dp))

            // 기념일 목록
            if (allAnniversaries.isEmpty()) {
                Box(
                    modifier = Modifier.fillMaxSize(),
                    contentAlignment = Alignment.Center
                ) {
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.spacedBy(16.dp)
                    ) {
                        Icon(
                            Icons.Default.Cake,
                            contentDescription = null,
                            modifier = Modifier.size(64.dp),
                            tint = Color(0xFF5D4037).copy(alpha = 0.3f)
                        )
                        Text(
                            text = if (relationshipStartDate == null) 
                                "프로필에서 사귀기 시작한 날을 입력하세요"
                            else
                                "아직 추가된 기념일이 없어요",
                            style = MaterialTheme.typography.bodyLarge,
                            color = Color(0xFF5D4037).copy(alpha = 0.5f)
                        )
                    }
                }
            } else {
                LazyColumn(
                    verticalArrangement = Arrangement.spacedBy(12.dp),
                    modifier = Modifier.weight(1f)
                ) {
                    items(allAnniversaries) { anniversary ->
                        AnniversaryCard(
                            anniversary = anniversary,
                            relationshipStartDate = relationshipStartDate,
                            onDelete = if (!anniversary.isAutoGenerated && anniversary.id > 0) {
                                {
                                    scope.launch {
                                        try {
                                            eventDao.deleteEvent(
                                                Event(
                                                    id = anniversary.id,
                                                    title = anniversary.title,
                                                    date = anniversary.date,
                                                    endDate = anniversary.date,
                                                    isAnniversary = true,
                                                        color = anniversary.color
                                                )
                                            )
                                        } catch (e: Exception) {
                                            e.printStackTrace()
                                        }
                                    }
                                }
                            } else null
                        )
                    }
                }
            }
        }

        // 추가 버튼
        FloatingActionButton(
            onClick = { showAddDialog = true },
            modifier = Modifier
                .align(Alignment.BottomEnd)
                .padding(20.dp),
            containerColor = Color(0xFFE91E63),
            contentColor = Color.White
        ) {
            Icon(
                Icons.Default.Add,
                contentDescription = "기념일 추가"
            )
        }
    }

    // 추가 다이얼로그
    if (showAddDialog) {
        AddAnniversaryDialog(
            onDismiss = { showAddDialog = false },
            onAdd = { title, date, color ->
                scope.launch {
                    try {
                        eventDao.insertEvent(
                            Event(
                                title = title,
                                date = date,
                                endDate = date,
                                isAnniversary = true,
                                color = color.ifBlank { DEFAULT_ANNIVERSARY_COLOR_HEX }
                            )
                        )
                        showAddDialog = false
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
                }
            }
        )
    }
}

@Composable
fun AnniversaryCard(
    anniversary: Anniversary,
    relationshipStartDate: LocalDate?,
    onDelete: (() -> Unit)? = null
) {
    val daysUntil = remember(anniversary.date) {
        try {
            val anniversaryDate = LocalDate.parse(anniversary.date, DateTimeFormatter.ISO_LOCAL_DATE)
            val today = LocalDate.now()
            ChronoUnit.DAYS.between(today, anniversaryDate).toInt()
        } catch (e: Exception) {
            null
        }
    }
    
    var showDeleteConfirm by remember { mutableStateOf(false) }

    val baseColor = remember(anniversary.color) {
        parseColorOrFallback(anniversary.color, Color(0xFFFFE0E0))
    }
    val containerColor = baseColor.copy(alpha = 0.25f)
    val accentColor = baseColor.copy(alpha = 0.55f)
    val highlightColor = baseColor.copy(alpha = 0.9f)
    
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(16.dp),
        colors = CardDefaults.cardColors(
            containerColor = containerColor
        ),
        border = BorderStroke(1.dp, baseColor.copy(alpha = 0.45f)),
        elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(20.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            // 아이콘
            Box(
                modifier = Modifier
                    .size(48.dp)
                    .background(
                        accentColor.copy(alpha = 0.6f),
                        RoundedCornerShape(12.dp)
                    ),
                contentAlignment = Alignment.Center
            ) {
                Icon(
                    if (anniversary.isAutoGenerated) Icons.Default.FavoriteBorder else Icons.Default.Cake,
                    contentDescription = null,
                    modifier = Modifier.size(28.dp),
                    tint = highlightColor
                )
            }

            Spacer(modifier = Modifier.width(16.dp))

            // 텍스트
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = anniversary.title,
                    style = MaterialTheme.typography.titleMedium.copy(
                        fontWeight = FontWeight.SemiBold,
                        fontSize = 16.sp
                    ),
                    color = Color(0xFF5D4037)
                )
                Spacer(modifier = Modifier.height(4.dp))
                Row(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = anniversary.date,
                        style = MaterialTheme.typography.bodyMedium,
                        color = Color(0xFF5D4037).copy(alpha = 0.6f)
                    )
                    daysUntil?.let { days ->
                        if (days >= 0) {
                            Text(
                                text = if (days == 0) "오늘!" else "D-$days",
                                style = MaterialTheme.typography.bodySmall.copy(
                                    fontWeight = FontWeight.Bold
                                ),
                                color = highlightColor
                            )
                        }
                    }
                }
            }
            
            // 삭제 버튼 (사용자가 추가한 기념일만)
            if (onDelete != null) {
                IconButton(
                    onClick = { showDeleteConfirm = true },
                    modifier = Modifier.size(32.dp)
                ) {
                    Icon(
                        Icons.Default.Delete,
                        contentDescription = "삭제",
                        tint = highlightColor,
                        modifier = Modifier.size(20.dp)
                    )
                }
            }
        }
    }
    
    if (showDeleteConfirm) {
        AlertDialog(
            onDismissRequest = { showDeleteConfirm = false },
            title = { Text("기념일 삭제") },
            text = { Text("이 기념일을 삭제하시겠습니까?") },
            confirmButton = {
                TextButton(
                    onClick = {
                        onDelete?.invoke()
                        showDeleteConfirm = false
                    }
                ) {
                    Text("삭제")
                }
            },
            dismissButton = {
                TextButton(onClick = { showDeleteConfirm = false }) {
                    Text("취소")
                }
            }
        )
    }
}

// 자동 기념일 계산 함수
fun calculateAutoAnniversaries(startDate: LocalDate): List<Anniversary> {
    val today = LocalDate.now()
    val anniversaries = mutableListOf<Anniversary>()
    
    // 100일, 200일, 300일, ... 단위 기념일
    for (days in 100..1000 step 100) {
        val anniversaryDate = startDate.plusDays(days.toLong())
        if (!anniversaryDate.isBefore(today)) { // 오늘 이후 날짜만 추가
            anniversaries.add(
                Anniversary(
                    title = "${days}일",
                    date = anniversaryDate.format(DateTimeFormatter.ISO_LOCAL_DATE),
                    color = DEFAULT_ANNIVERSARY_COLOR_HEX,
                    isAutoGenerated = true
                )
            )
        }
    }
    
    // 주년 기념일 (1주년, 2주년, ...)
    for (year in 1..10) {
        val anniversaryDate = startDate.plusYears(year.toLong())
        if (!anniversaryDate.isBefore(today)) { // 오늘 이후 날짜만 추가
            anniversaries.add(
                Anniversary(
                    title = "${year}주년",
                    date = anniversaryDate.format(DateTimeFormatter.ISO_LOCAL_DATE),
                    color = DEFAULT_ANNIVERSARY_COLOR_HEX,
                    isAutoGenerated = true
                )
            )
        }
    }
    
    return anniversaries.sortedBy { it.date }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddAnniversaryDialog(
    onDismiss: () -> Unit,
    onAdd: (String, String, String) -> Unit
) {
    var title by remember { mutableStateOf("") }
    var date by remember { mutableStateOf("") }
    var showDatePicker by remember { mutableStateOf(false) }
    var selectedColor by remember { mutableStateOf(DEFAULT_ANNIVERSARY_COLOR_HEX) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = "기념일 추가",
                style = MaterialTheme.typography.titleLarge.copy(
                    fontWeight = FontWeight.Bold
                )
            )
        },
        text = {
            Column(
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                OutlinedTextField(
                    value = title,
                    onValueChange = { title = it },
                    label = { Text("기념일 이름") },
                    placeholder = { Text("예: 우리 만난날, 생일") },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true
                )
                OutlinedTextField(
                    value = date,
                    onValueChange = { },
                    label = { Text("날짜") },
                    placeholder = { Text("날짜를 선택하세요") },
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable { showDatePicker = true },
                    readOnly = true,
                    trailingIcon = {
                        IconButton(onClick = { showDatePicker = true }) {
                            Icon(Icons.Default.CalendarToday, contentDescription = "달력")
                        }
                    },
                    singleLine = true,
                    enabled = false,
                    colors = OutlinedTextFieldDefaults.colors(
                        disabledTextColor = MaterialTheme.colorScheme.onSurface,
                        disabledBorderColor = MaterialTheme.colorScheme.outline,
                        disabledLeadingIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        disabledTrailingIconColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        disabledLabelColor = MaterialTheme.colorScheme.onSurfaceVariant,
                        disabledPlaceholderColor = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                )

                Text(
                    text = "색상 선택",
                    style = MaterialTheme.typography.labelLarge.copy(fontWeight = FontWeight.SemiBold),
                    color = Color(0xFF5D4037)
                )

                LazyRow(
                    horizontalArrangement = Arrangement.spacedBy(12.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    items(ANNIVERSARY_COLOR_OPTIONS) { colorHex ->
                        val color = parseColorOrFallback(colorHex, Color(0xFFFFE0E0))
                        val isSelected = selectedColor == colorHex

                        Box(
                            modifier = Modifier
                                .size(if (isSelected) 40.dp else 36.dp)
                                .clip(CircleShape)
                                .background(color)
                                .border(
                                    width = if (isSelected) 3.dp else 1.dp,
                                    color = if (isSelected) Color.White else Color(0x335D4037),
                                    shape = CircleShape
                                )
                                .clickable { selectedColor = colorHex },
                            contentAlignment = Alignment.Center
                        ) {
                            if (isSelected) {
                                Icon(
                                    imageVector = Icons.Default.Check,
                                    contentDescription = null,
                                    tint = Color(0xFF5D4037),
                                    modifier = Modifier.size(20.dp)
                                )
                            }
                        }
                    }
                }
            }
        },
        confirmButton = {
            TextButton(
                onClick = {
                    if (title.isNotEmpty() && date.isNotEmpty()) {
                        onAdd(title, date, selectedColor)
                    }
                },
                enabled = title.isNotEmpty() && date.isNotEmpty()
            ) {
                Text("추가")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("취소")
            }
        }
    )
    
    // DatePicker
    if (showDatePicker) {
        val datePickerState = rememberDatePickerState()
        
        DatePickerDialog(
            onDismissRequest = { showDatePicker = false },
            confirmButton = {
                TextButton(
                    onClick = {
                        datePickerState.selectedDateMillis?.let { millis ->
                            val localDate = Instant.ofEpochMilli(millis)
                                .atZone(ZoneId.systemDefault())
                                .toLocalDate()
                            date = localDate.format(DateTimeFormatter.ISO_LOCAL_DATE)
                        }
                        showDatePicker = false
                    }
                ) {
                    Text("확인")
                }
            },
            dismissButton = {
                TextButton(onClick = { showDatePicker = false }) {
                    Text("취소")
                }
            }
        ) {
            Column {
                Text(
                    text = "기념일 날짜를 선택해주세요",
                    style = MaterialTheme.typography.titleLarge.copy(
                        fontWeight = FontWeight.Bold
                    ),
                    modifier = Modifier.padding(start = 24.dp, end = 24.dp, top = 16.dp, bottom = 8.dp)
                )
                DatePicker(
                    state = datePickerState,
                    title = null,
                    headline = null
                )
            }
        }
    }
}

data class Anniversary(
    val id: Long = 0,
    val title: String,
    val date: String,
    val color: String = DEFAULT_ANNIVERSARY_COLOR_HEX,
    val isAutoGenerated: Boolean = false // 자동 생성된 기념일인지 여부
)

private const val DEFAULT_ANNIVERSARY_COLOR_HEX = "#FFE0E0"
private val ANNIVERSARY_COLOR_OPTIONS = listOf(
    DEFAULT_ANNIVERSARY_COLOR_HEX,
    "#FFCDD2",
    "#F8BBD0",
    "#E1BEE7",
    "#D1C4E9",
    "#C5CAE9",
    "#BBDEFB",
    "#B2EBF2",
    "#C8E6C9",
    "#FFF9C4",
    "#FFE0B2",
    "#FFCCBC"
)

private fun parseColorOrFallback(hex: String, fallback: Color): Color {
    return runCatching { Color(AndroidColor.parseColor(hex)) }.getOrElse { fallback }
}

